.PHONY: clean All

All:
	@echo "----------Building project:[ 3.3-spindel - Debug ]----------"
	@cd "3.3-spindel" && "$(MAKE)" -f  "3.3-spindel.mk" && "$(MAKE)" -f  "3.3-spindel.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 3.3-spindel - Debug ]----------"
	@cd "3.3-spindel" && "$(MAKE)" -f  "3.3-spindel.mk" clean
