.PHONY: clean All

All:
	@echo "----------Building project:[ 4.3-labb - Debug ]----------"
	@cd "4.3-labb" && "$(MAKE)" -f  "4.3-labb.mk" && "$(MAKE)" -f  "4.3-labb.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 4.3-labb - Debug ]----------"
	@cd "4.3-labb" && "$(MAKE)" -f  "4.3-labb.mk" clean
