.PHONY: clean All

All:
	@echo "----------Building project:[ Spindeljakt-modified - Debug ]----------"
	@cd "Spindeljakt-modified" && "$(MAKE)" -f  "Spindeljakt-modified.mk" && "$(MAKE)" -f  "Spindeljakt-modified.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Spindeljakt-modified - Debug ]----------"
	@cd "Spindeljakt-modified" && "$(MAKE)" -f  "Spindeljakt-modified.mk" clean
